<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Malin_SSS_AT2</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AstroMathLib">
      <HintPath>..\AstroMath\bin\Debug\netstandard2.0\AstroMathLib.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
